#-------------------------------
# General Site Settings
title: Yung-Tang C. 
logo: # You can add own logo. For example '/images/logo.png'.
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: Yung-Tang (Patrick) Chou
  bio: Hi, this is my personal blog for my data science blogging. As I learn new things in the field of data science, I'll constantly update this blog to take some notes for later reflection.
  image: '/images/01.jpg'
  avatar: '/images/15.jpg'

# Example of adding a new link to the section author - {name: "Github", link: "https://github.com"}
author-social:
- {name: "Facebook", link: "https://www.facebook.com/patrick.chou.5"}
- {name: "Linkedin", link: "https://www.linkedin.com/in/yungtang-chou/"}
- {name: "Github", link: "https://github.com/patrick-ytchou/Data-Science"}

#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com
contact:
- {icon: "ion-logo-facebook", link: "https://www.facebook.com/patrick.chou.5"}
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/yungtang-chou/"}
- {icon: "ion-logo-github", link: "https://github.com/patrick-ytchou/Data-Science"}


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr.C. # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
userID: 6716400487
accessToken: 6716400487.1677ed0.4fae51c47bc544a895b81756a7d0c477


#-------------------------------
# Google Analytics
google-analytics: "UA-162704821-1" # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: false # To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 10
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed